use_gpu: True
gpu_id: 0
seed: 2022
save_dataset: False
save_dataloaders: False
USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
    inter: [session_id, item_id, timestamp]
user_inter_num_interval: "[2,inf)"
item_inter_num_interval: "[5,inf)"
training_neg_sample_num: 0
POSITION_FIELD: position_id
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 20
epochs: 1000
train_batch_size: 512
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 5
eval_setting: TO_LS,full
group_by_user: True
split_ratio: [0.8,0.1,0.1]
metrics: ["Recall", "MRR", "NDCG", "Hit", "Precision"]
topk: [20]
valid_metric: MRR@20
eval_batch_size: 512
reg_weight: 5e-5
hidden_size: 100
inner_size: 400
step: 1
gnn_attention_layers: 1
gnn_attention_heads: 1
gnn_attention_dropout_prob: 0.2
gnn_attention_hidden_dropout_prob: 0.2
gnn_attention_hidden_act: gelu
rnn_layers: 1
rnn_attention_layers: 1
rnn_attention_heads: 1
rnn_attention_dropout_prob: 0.2
rnn_attention_hidden_dropout_prob: 0.2
rnn_attention_hidden_act: gelu
layer_norm_eps: 1e-12
initializer_range: 0.01
loss_type: CE
